export interface State{
  viewValue: string;
  }

export const usStates: State[] = [
{viewValue:"AK - Alaska"},
{viewValue:"AL - Alabama"},
{viewValue:"AR - Arkansas"},
{viewValue:"AS - American Samoa"},
{viewValue:"AZ - Arizona"},
{viewValue:"CA - California"},
{viewValue:"CO - Colorado"},
{viewValue:"CT - Connecticut"},
{viewValue:"DC - District of Columbia"},
{viewValue:"DE - Delaware"},
{viewValue:"FL - Florida"},
{viewValue:"GA - Georgia"},
{viewValue:"HI - Hawaii"},
{viewValue:"IA - Iowa"},
{viewValue:"ID - Idaho"},
{viewValue:"IL - Illinois"},
{viewValue:"IN - Indiana"},
{viewValue:"KS - Kansas"},
{viewValue:"KY - Kentucky"},
{viewValue:"LA - Louisiana"},
{viewValue:"MA - Massachusetts"},
{viewValue:"MD - Maryland"},
{viewValue:"ME - Maine"},
{viewValue:"MI - Michigan"},
{viewValue:"MN - Minnesota"},
{viewValue:"MO - Missouri"},
{viewValue:"MS - Mississippi"},
{viewValue:"MT - Montana"},
{viewValue:"NC - North Carolina"},
{viewValue:"ND - North Dakota"},
{viewValue:"NE - Nebraska"},
{viewValue:"NH - New Hampshire"},
{viewValue:"NJ - New Jersey"},
{viewValue:"NM - New Mexico"},
{viewValue:"NV - Nevada"},
{viewValue:"NY - New York"},
{viewValue:"OH - Ohio"},
{viewValue:"OK - Oklahoma"},
{viewValue:"OR - Oregon"},
{viewValue:"PA - Pennsylvania"},
{viewValue:"RI - Rhode Island"},
{viewValue:"SC - South Carolina"},
{viewValue:"SD - South Dakota"},
{viewValue:"TN - Tennessee"},
{viewValue:"TX - Texas"},
{viewValue:"UT - Utah"},
{viewValue:"VA - Virginia"},
{viewValue:"VI - Virgin Islands"},
{viewValue:"VT - Vermont"},
{viewValue:"WA - Washington"},
{viewValue:"WI - Wisconsin"},
{viewValue:"WV - West Virginia"},
{viewValue:"WY - Wyoming"}
]

