export interface State{
  value: string;
  }

export const usStates:[ 
{ viewValue:"AK - Alaska"}, 
{viewValue:"AL - Alabama"}, 
{viewValue:"AR - Arkansas"}, 
{viewValue:"AS - American Samoa"}, 
{viewValue:"AZ - Arizona"}, 
{viewValue:"CA - California"}, 
{viewValue:"CO - Colorado"}, 
{viewValue:"CT - Connecticut"}, 
{viewValue:"DC - District of Columbia"}, 
{viewValue:"DE - Delaware"}, 
{viewValue:"FL - Florida"}, 
{viewValue:"GA - Georgia"}, 
{viewValue:"HI - Hawaii"}, 
{viewValue:"IA - Iowa"}, 
{viewValue:"ID - Idaho"}, 
{viewValue:"IL - Illinois"}, 
{viewValue:"IN - Indiana"}, 
{viewValue:"KS - Kansas"}, 
{viewValue:"KY - Kentucky"}, 
{viewValue:"LA - Louisiana"}, 
{viewValue:"MA - Massachusetts"}, 
{viewValue:"MD - Maryland"}, 
{viewValue:"ME - Maine"}, 
{viewValue:"MI - Michigan"}, 
{viewValue:"MN - Minnesota"}, 
{viewValue:"MO - Missouri"}, 
"MS - Mississippi", 
"MT - Montana", 
"NC - North Carolina", 
"ND - North Dakota", 
"NE - Nebraska", 
"NH - New Hampshire", 
"NJ - New Jersey", 
"NM - New Mexico", 
"NV - Nevada", 
"NY - New York", 
"OH - Ohio", 
"OK - Oklahoma", 
"OR - Oregon", 
"PA - Pennsylvania", 
"PR - Puerto Rico", 
"RI - Rhode Island", 
"SC - South Carolina", 
"SD - South Dakota", 
"TN - Tennessee", 
"TX - Texas", 
"UT - Utah", 
"VA - Virginia", 
"VI - Virgin Islands", 
"VT - Vermont", 
"WA - Washington", 
"WI - Wisconsin", 
"WV - West Virginia", 
"WY - Wyoming"]

